import React, { useState } from 'react';
import { LayoutDashboard, TrendingUp, Target, Users, AlertCircle, CheckCircle } from 'lucide-react';
import { useToast } from './Toast';
import './SalesInsightsEngine.css';

const SalesInsightsEngine = ({ customer, onActionClick, onUpdateCustomer }) => {
  const { addToast } = useToast();
  const [isAccepting, setIsAccepting] = useState(false);

  const handleAcceptCustomer = async () => {
    if (!customer || !customer.id) return;
    setIsAccepting(true);
    
    try {
      const res = await fetch(`/api/customers/${customer.id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ status: 'Active' })
      });
      const data = await res.json();
      
      if (data.success) {
        addToast("Customer accepted! Status changed to Active.", "success");
        if (onUpdateCustomer) {
          onUpdateCustomer({ status: 'Active' });
        }
      } else {
        addToast(data.message || "Failed to update status", "error");
      }
    } catch (err) {
      addToast("Network error while updating status", "error");
    } finally {
      setIsAccepting(false);
    }
  };

  return (
    <div className="insights-engine animate-fade-in">
      <div className="engine-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '1rem' }}>
        <div>
          <h1 className="engine-title">Sales Insights Engine</h1>
          <p className="engine-subtitle">Real-time centralized AI intelligence derived from your CRM data.</p>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
          {customer && customer.status !== 'Active' && (
            <button 
              className="btn flex-center"
              style={{
                background: 'var(--color-accent)', 
                color: 'var(--color-surface)',
                border: 'none',
                padding: '10px 24px',
                borderRadius: '100px',
                fontWeight: 600,
                cursor: isAccepting ? 'not-allowed' : 'pointer',
                opacity: isAccepting ? 0.7 : 1,
                boxShadow: 'var(--shadow-md)',
                transition: 'all 0.2s',
                gap: '8px'
              }}
              onClick={handleAcceptCustomer}
              disabled={isAccepting}
            >
              <CheckCircle size={18} />
              {isAccepting ? "Accepting..." : "Accept Customer"}
            </button>
          )}
          <div className="engine-status glass-panel">
            <span className="pulse-dot"></span> AI Models Active
          </div>
        </div>
      </div>

      <div className="metrics-overview">
        <div className="metric-card glass-panel delay-1 animate-fade-in">
          <div className="metric-icon bg-gold-light text-accent"><TrendingUp size={24} /></div>
          <div className="metric-data">
            <span className="metric-label">Pipeline Health Score</span>
            <span className="metric-value">92/100</span>
          </div>
        </div>
        
        <div className="metric-card glass-panel delay-2 animate-fade-in">
          <div className="metric-icon bg-blue-light text-blue"><Target size={24} /></div>
          <div className="metric-data">
            <span className="metric-label">Predicted Win Rate</span>
            <span className="metric-value">68%</span>
          </div>
        </div>

        <div className="metric-card glass-panel delay-3 animate-fade-in">
          <div className="metric-icon bg-dark-light text-dark"><Users size={24} /></div>
          <div className="metric-data">
            <span className="metric-label">Active Engagements</span>
            <span className="metric-value">142</span>
          </div>
        </div>
      </div>

      <div className="engine-grid">
        {/* Main AI Recommendations Panel */}
        <div className="glass-panel recommendations-panel span-2">
          <div className="card-header">
            <h3 className="card-title"><LayoutDashboard size={20} className="text-accent" /> Priority Actions Generated by AI</h3>
          </div>
          <div className="actions-list">
            
            <div className="action-item vital">
              <div className="action-priority">High Priority</div>
              <div className="action-content">
                <h4>Reach out to TechFlow Inc. (Decision Maker Hesitant)</h4>
                <p>AI Emotion Analyzer detected hesitation in Sarah Jenkins' latest email. The Deal Predictor shows a 15% drop in win probability if unaddressed.</p>
                <div className="action-buttons">
                  <button 
                    className="btn-accent" 
                    style={{padding: '6px 16px', fontSize: '0.9rem'}}
                    onClick={() => {
                      addToast("Opening Email Generator...", "info");
                      if (onActionClick) onActionClick('email');
                    }}
                  >
                    Draft Reassuring Email
                  </button>
                  <button 
                    className="btn-primary" 
                    style={{padding: '6px 16px', fontSize: '0.9rem', background: 'transparent', color: 'var(--color-dark-charcoal)'}}
                    onClick={() => {
                      addToast("Opening Account Summarizer...", "info");
                      if (onActionClick) onActionClick('account');
                    }}
                  >
                    View Account
                  </button>
                </div>
              </div>
            </div>

            <div className="action-item standard">
              <div className="action-priority">Actionable</div>
              <div className="action-content">
                <h4>Generate Proposal for Global Logistics Solutions</h4>
                <p>Opportunity Analyzer indicates they have passed the Technical Review stage. Generate standard enterprise proposal to accelerate closing.</p>
                <div className="action-buttons">
                  <button 
                    className="btn-primary" 
                    style={{padding: '6px 16px', fontSize: '0.9rem'}}
                    onClick={() => {
                      addToast("Opening Proposal Generator...", "info");
                      if (onActionClick) onActionClick('proposal');
                    }}
                  >
                    Auto-Generate Proposal
                  </button>
                </div>
              </div>
            </div>

          </div>
        </div>

        {/* Global Risks Panel */}
        <div className="glass-panel risk-panel">
          <div className="card-header">
            <h3 className="card-title"><AlertCircle size={20} style={{color: '#FF5F56'}} /> Network Risks</h3>
          </div>
          <div className="risk-alerts">
            <div className="risk-alert">
              <strong>Competitor Surge:</strong> Mentions of "Competitor X" have increased by 40% across all calls this week.
            </div>
            <div className="risk-alert">
              <strong>Engagement Drop:</strong> The average response time from Enterprise leads has increased from 4h to 18h.
            </div>
          </div>
          
          <div className="ai-coach-mini mt-4">
            <h4>Sales Coach Tip</h4>
            <p>Ensure your next 5 cold emails focus heavily on our unique fast-implementation differentiator to combat Competitor X.</p>
          </div>
        </div>
      </div>

    </div>
  );
};

export default SalesInsightsEngine;
